### ISSUE TITLE
Noetic Release

### ISSUE THREAD

**Issue by matthew-reynolds** [ros-controls/urdf_geometry_parser#18]
I think this package is ready for a Noetic release, but I just wanted to start the conversation rolling.

The only potential consideration is if we want to do a big overhaul of the package to make it less of a "fetcher and parser" and more of a pure "parser". And also if we want to switch from `rosconsole` outputs to error strings. See https://github.com/ros-controls/urdf_geometry_parser/issues/10#issuecomment-610019711.

If that happens, it should definitely either be a pre-`Noetic` change or a complete new package (`urdf_geometry_parser2`, anyone? :sunglasses:).

**Comment by bmagyar** [comment]
Noetic release is out
